Pig Stack Trace
---------------
ERROR 6000: 
<file graph.pig, line 7, column 0> Output Location Validation Failed for: 'file:///home/gshastri/project6/output More info to follow:
Output directory file:/home/gshastri/project6/output already exists

org.apache.pig.impl.plan.VisitorException: ERROR 6000: 
<file graph.pig, line 7, column 0> Output Location Validation Failed for: 'file:///home/gshastri/project6/output More info to follow:
Output directory file:/home/gshastri/project6/output already exists
	at org.apache.pig.newplan.logical.visitor.InputOutputFileValidatorVisitor.visit(InputOutputFileValidatorVisitor.java:95)
	at org.apache.pig.newplan.logical.relational.LOStore.accept(LOStore.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:64)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.walk(DepthFirstWalker.java:53)
	at org.apache.pig.newplan.PlanVisitor.visit(PlanVisitor.java:52)
	at org.apache.pig.newplan.logical.relational.LogicalPlan.validate(LogicalPlan.java:212)
	at org.apache.pig.PigServer$Graph.compile(PigServer.java:1851)
	at org.apache.pig.PigServer$Graph.access$300(PigServer.java:1527)
	at org.apache.pig.PigServer.execute(PigServer.java:1440)
	at org.apache.pig.PigServer.executeBatch(PigServer.java:488)
	at org.apache.pig.PigServer.executeBatch(PigServer.java:471)
	at org.apache.pig.tools.grunt.GruntParser.executeBatch(GruntParser.java:172)
	at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:235)
	at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:206)
	at org.apache.pig.tools.grunt.Grunt.exec(Grunt.java:81)
	at org.apache.pig.Main.run(Main.java:630)
	at org.apache.pig.Main.main(Main.java:176)
Caused by: org.apache.hadoop.mapred.FileAlreadyExistsException: Output directory file:/home/gshastri/project6/output already exists
	at org.apache.hadoop.mapreduce.lib.output.FileOutputFormat.checkOutputSpecs(FileOutputFormat.java:137)
	at org.apache.pig.newplan.logical.visitor.InputOutputFileValidatorVisitor.visit(InputOutputFileValidatorVisitor.java:69)
	... 21 more
================================================================================
